sentence = input('Type something to say: ')
length = len(sentence)
print('         {}'.format('_' * length))
print('       < {} >'.format(sentence))
print('         {}'.format('-' * length))
print('        /')
print(' /\_/\ /')
print('( o.o )')
print(' > ^ <')
